export const projectsData = [
    {
        id: 1,
        src: "/images/projects/work1.jpg",
        category: "AI & Immersive Experiences",
        title: "Visit Saudi | Verofax",
        link: "/visit-saudi",
    },
    {
        id: 2,
        src: "/images/projects/work2.jpg",
        category: "Branding",
        title: "Zeila Coffee Shop",
        link: "/zeila-coffee-shop",
    },
      {
        id: 3,
        src: "/images/projects/work3.jpg",
        category: "AI & Immersive Experiences",
        title: "AFA | Verofans",
        link: "/afa-verofans",
    },
      {
        id: 4,
        src: "/images/projects/work4.jpg",
        category: "Branding",
        title: "Kaf Concept",
        link: "/kaf-concept",
    },
    {
        id: 5,
        src: "/images/projects/work5.jpg",
        category: "Marketing & Social",
        title: "PROVOC Makeup",
        link: "/provoc-makeup",
    },
 {
        id: 6,
        src: "/images/projects/work6.jpg",
        category: "AI & Immersive Experiences",
        title: "Budweiser | Verofax",
        link: "/budweiser-verofax",
    },
     {
        id: 7,
        src: "/images/projects/work7.jpg",
        category: "Branding",
        title: "AZALEA",
        link: "/azalea",
    },
     {
        id: 8,
        src: "/images/projects/work8.jpg",
        category: "Branding",
        title: "SAM Audit",
        link: "/sam-audit",
    },
  {
        id: 9,
        src: "/images/projects/work9.jpg",
        category: "Marketing & Social",
        title: "Popkitch",
        link: "/popkitch",
    },
       {
        id: 10,
        src: "/images/projects/work10.jpg",
        category: "Digital Design",
        title: "GGI Website Design",
        link: "/ggi-website-design",
    },
        {
        id: 11,
        src: "/images/projects/work11.jpg",
        category: "Branding",
        title: "KAEC",
        link: "/kaec",
    },
    {
        id: 12,
        src: "/images/projects/work12.jpg",
        category: "Branding",
        title: "Industrial Valley",
        link: "/industrial-valley",
    },
        {
        id: 13,
        src: "/images/projects/work13.jpg",
        category: "Branding",
        title: "Datanet Global",
        link: "/datanet-global",
    },
            {
        id: 14,
        src: "/images/projects/work14.jpg",
        category: "Branding",
        title: "Iconic Beauty Salon",
        link: "/iconic-beauty-salon",
    },
              {
        id: 15,
        src: "/images/projects/work15.jpg",
        category: "Branding",
        title: "Diana Rizk",
        link: "/diana-rizk",
    },
]
